### PR TITLE
Convert Cypress Tests to TypeScript

### LINKED ISSUE #5: Convert Cypress tests to TypeScript
Right now, Cutiekey uses vanilla JavaScript to run E2E tests. These tests should be converted to TypeScript in order to properly type the test files, as well as helping catch common pitfalls when testing.

### PR DESCRIPTION
**Pull request by lunaisnotaboy**
See #5 for more details.

### CODE REVIEW

**Review by lexi-the-cute — APPROVED** [review]

**Comment by dakkar** [comment]
(hi! looking at this for inclusion in Sharkey, as you asked)

so, the changes seem to be:
* renaming the files
* translating the Japanese / fixing the English
* changing the indentation
* little else

Is changing the name of the files enough to have them interpreted as TypeScript by editors/IDEs? I don't see any typing information anywhere, so I guess we don't really need to annotate the tests with types?

If that's right, we can probably rename the files in Sharkey (assuming we can get `git` to understand that changes to .e.g `basic.cy.js` upstream need to be applied to `basic.cy.ts`), or even better we can ask Misskey to rename them.

**Comment by lunaisnotaboy** [comment]
> Is changing the name of the files enough to have them interpreted as TypeScript by editors/IDEs?

Since they are included by the `tsconfig.json` file in the `cypress` folder, yes, IDEs should automatically pick up the applicable types.

> I don't see any typing information anywhere, so I guess we don't really need to annotate the tests with types?

No, there is. Look at the `cypress/support/index.ts` file. That contains typing information for the custom commands in `cypress/support/commands.ts`. Without these types, chaining the functions would not work, causing us to fall into common pitfalls when writing new types.

> If that's right, we can probably rename the files in Sharkey (assuming we can get `git` to understand that changes to .e.g `basic.cy.js` upstream need to be applied to `basic.cy.ts`), or even better we can ask Misskey to rename them.

That's what I did here. Apparently, Git didn't pick up on it.

**Comment by lunaisnotaboy** [comment]
(As for indentation, I use spaces instead of tabs, and that's what this fork is going to use. If I merge this into Sharkey, then I will obviously change it to tabs.)

**Comment by dakkar** [comment]
aah, I hadn't noticed the two new files! (I was mostly trying to see the changes to the existing files)

git didn't pick up the renames because… well, mostly because git does not know what a "rename" even is, but also because you renamed + edited the files in a single commit; that's why I'm very wary of merging changes like these in Sharkey: any upstream change to the renamed files will cause merge conflicts

I think this change is useful enough that we could send a PR to Misskey, with just the strictly needed bits: rename the files, add the `index.ts` and `tsconfig.json`. I guess that `pnpm cy:run` and `pnpm cy:open` still work fine?

**Comment by lunaisnotaboy** [comment]
Yeah, the commands still work. I should note that I picked up a test that wasn't done correctly because of the lack of typings (I can't remember _which_ test OTTOMH), so I also think it's worth at least _discussing_ merging the whole files into Misskey.

**Comment by lunaisnotaboy** [comment]
(Apparently, Git _does_ [have support for renaming things](https://git-scm.com/docs/git-mv)... TIL!)

**Comment by dakkar** [comment]
> merging the whole files into Misskey

I now feel I've missed something. This PR renames a few files, adds a `index.ts`, a `tsconfig.json`, translates some Japanese into English, changes the indentation, and moves some sub-tests around.

I was under the impression that the only *necessary* bits where the renames and the two new files. What "whole files" do you mean? What am I missing?

**Comment by lunaisnotaboy** [comment]
Misspoke, my apologies. I was still thinking along those lines. I'll find that test and send it to you, then you can do what you see fit.

**Comment by dakkar** [comment]
right, I'll prepare a PR for misskey with the rename and your new files, I'll ask you to double-check I've done the right thing, then send it

**Pull request merged**
