### PR TITLE
Convert references to "Sharkey" to "Cutiekey"

### PR DESCRIPTION
**Pull request by lunaisnotaboy**
We want to make sure that we're not referring to "Sharkey" in the UI so we don't confuse people.

### CODE REVIEW

**Comment by ChaoticLeah** [comment]
This all seems fine. Maybe you can use
```
   _____      _   _      _              
  / ____|    | | (_)    | |             
 | |    _   _| |_ _  ___| | _____ _   _ 
 | |   | | | | __| |/ _ \ |/ / _ \ | | |
 | |___| |_| | |_| |  __/   <  __/ |_| |
  \_____\__,_|\__|_|\___|_|\_\___|\__, |
                                   __/ |
                                  |___/ 
```
in the places you removed the big sharkey ascii logo.

Also I'm not sure about the docker and automated building stuff

**Comment by lunaisnotaboy** [comment]
> This all seems fine. Maybe you can use
> 
> ```
>    _____      _   _      _              
>   / ____|    | | (_)    | |             
>  | |    _   _| |_ _  ___| | _____ _   _ 
>  | |   | | | | __| |/ _ \ |/ / _ \ | | |
>  | |___| |_| | |_| |  __/   <  __/ |_| |
>   \_____\__,_|\__|_|\___|_|\_\___|\__, |
>                                    __/ |
>                                   |___/ 
> ```
> 
> in the places you removed the big sharkey ascii logo.
> 
> Also I'm not sure about the docker and automated building stuff

Would this work?

```
 _____     _   _     _
|     |_ _| |_|_|___| |_ ___ _ _
|   --| | |  _| | -_| '_| -_| | |
|_____|___|_| |_|___|_,_|___|_  |
                            |___|
```

**Comment by ChaoticLeah** [comment]
> > This all seems fine. Maybe you can use
> > ```
> >    _____      _   _      _              
> >   / ____|    | | (_)    | |             
> >  | |    _   _| |_ _  ___| | _____ _   _ 
> >  | |   | | | | __| |/ _ \ |/ / _ \ | | |
> >  | |___| |_| | |_| |  __/   <  __/ |_| |
> >   \_____\__,_|\__|_|\___|_|\_\___|\__, |
> >                                    __/ |
> >                                   |___/ 
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > in the places you removed the big sharkey ascii logo.
> > Also I'm not sure about the docker and automated building stuff
> 
> Would this work?
> 
> ```
>  _____     _   _     _
> |     |_ _| |_|_|___| |_ ___ _ _
> |   --| | |  _| | -_| '_| -_| | |
> |_____|___|_| |_|___|_,_|___|_  |
>                             |___|
> ```

Yeah that works

**Comment by lunaisnotaboy** [comment]
I'm not going to be adding a logo right now, as I don't have anything. I'll see what I can do.

**Review by ChaoticLeah — APPROVED** [review]
Everything looks good!

**Review by theresnotime — APPROVED** [review]
lgtm

**Review by theresnotime — APPROVED** [review]

**Pull request merged**
